{{- if .Values.secrets.vault.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portal.fullname" . }}-vault-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "portal-role"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ include "portal.fullname" . }}-vault-auth
  namespace: {{ .Release.Namespace }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: portal-role
    serviceAccount: {{ include "portal.fullname" . }}-vault-sa
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ include "portal.fullname" . }}-db-creds
  namespace: {{ .Release.Namespace }}
spec:
  mount: database
  path: creds/portal-db-role
  vaultAuthRef: {{ include "portal.fullname" . }}-vault-auth
  destination:
    name: portal-db-secret
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "portal.fullname" . }}-backend
{{- end }}

---
{{- if .Values.secrets.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "portal.fullname" . }}-sealed-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    jwt-secret: {{ .Values.secrets.sealedSecrets.jwtSecret | quote }}
    oauth-client-secret: {{ .Values.secrets.sealedSecrets.oauthClientSecret | quote }}
  template:
    metadata:
      name: portal-app-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-tls-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/issuer: {{ .Values.certificates.issuer }}
type: kubernetes.io/tls
data: {}

---
{{- if .Values.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "portal.fullname" . }}-external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval | default "15s" }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: portal-external-secrets
    creationPolicy: Owner
  data:
  - secretKey: aws-access-key-id
    remoteRef:
      key: portal/aws
      property: access-key-id
  - secretKey: aws-secret-access-key
    remoteRef:
      key: portal/aws
      property: secret-access-key
  - secretKey: gcp-credentials
    remoteRef:
      key: portal/gcp
      property: credentials
  - secretKey: azure-credentials
    remoteRef:
      key: portal/azure
      property: credentials
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-grafana-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/encoding: base64
type: Opaque
data:
  admin-password: {{ .Values.monitoring.grafana.adminPassword.password | default "" | b64enc }}

---
{{- if .Values.secrets.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "portal.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "portal.fullname" . }}-tls
  duration: {{ .Values.certificates.duration }}
  renewBefore: {{ .Values.certificates.renewBefore }}
  subject:
    organizations:
      - {{ .Values.certificates.organization | default "Multi-Cloud Portal" }}
  commonName: {{ .Values.ingress.hosts[0].host }}
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ .host }}
  {{- end }}
  issuerRef:
    name: {{ .Values.certificates.issuer }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-redis-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/length: "64"
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | default "" | b64enc }}