# Default values for self-service-portal
frontend:
  replicaCount: 2
  image:
    repository: ghcr.io/ruslanbaba/multi-cloud-k8s-standardization/portal-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: portal.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: portal-tls
        hosts:
          - portal.example.com
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

backend:
  replicaCount: 2
  image:
    repository: ghcr.io/ruslanbaba/multi-cloud-k8s-standardization/portal-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "3000"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
  
  secretRefs:
    - name: portal-secrets
      keys:
        - JWT_SECRET
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - GCP_CREDENTIALS
        - AZURE_CREDENTIALS

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

networkPolicy:
  enabled: true
  ingressRules:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
  grafanaDashboard:
    enabled: true
