# Argo CD Application manifest for unified multi-cloud deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-cloud-k8s
spec:
  project: default
  source:
    repoURL: https://github.com/ruslanbaba/Multi-Cloud-K8s-Standardization.git
    path: terraform
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
