apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: zero-trust-policy
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/*/sa/*"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/api/v1/*"]
    when:
    - key: request.auth.claims[iss]
      values: ["https://accounts.google.com"]

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: service-cert
spec:
  secretName: service-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Example Corp
  commonName: service.example.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - service.example.com
    - service.example.svc

---
apiVersion: security.gatekeeper.sh/v1beta1
kind: SecurityPolicy
metadata:
  name: pod-security
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    seccompProfiles:
      - runtime/default
    allowedCapabilities:
      - NET_BIND_SERVICE
    requiredDropCapabilities:
      - ALL
