apiVersion: postgresql.acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 100Gi
  numberOfInstances: 3
  users:
    app_user: []
  databases:
    app_db: app_user
  postgresql:
    version: "14"
  enableMasterPoolerLoadBalancer: true
  enableReplicaPoolerLoadBalancer: true
  
---
apiVersion: strimzi.io/v1beta2
kind: Kafka
metadata:
  name: event-streaming
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: route
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
