apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-monitoring
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: kubernetes-monitoring
  namespaceSelector:
    matchNames:
      - default
      - kube-system
  endpoints:
  - port: metrics
    interval: 15s
    scrapeTimeout: 14s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-alerts
  namespace: monitoring
spec:
  groups:
  - name: kubernetes-system
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        description: Pod {{ $labels.pod }} has high CPU usage
    - alert: MemoryUsage
      expr: sum(container_memory_usage_bytes) by (pod) > 2147483648
      for: 5m
      labels:
        severity: warning
      annotations:
        description: Pod {{ $labels.pod }} using more than 2GB of memory
