apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  enable-modsecurity: "true"
  enable-owasp-modsecurity-crs: "true"
  client-header-timeout: "60"
  client-body-timeout: "60"
  proxy-body-size: "20m"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
  enable-real-ip: "true"
  server-tokens: "false"
  
  # Rate limiting
  limit-rps: "10"
  limit-connections: "5"
  
  # Metrics
  enable-prometheus-metrics: "true"
  
  # Security headers
  add-headers: "ingress-nginx/custom-headers"
